server:
  port: 8400
spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: thw
    password: thw19971017thw
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
    tomcat:
      max-wait: 10000
      min-idle: 20
      max-idle: 100
      max-active: 300
  redis:
    host: 192.168.217.128
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 10000
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: java.util
  mapper-locations: mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
